# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['freeze_encoder', 'process_output']

# %% ../nbs/utils.ipynb 5
from .data import INT2TYPE
import re

# %% ../nbs/utils.ipynb 6
def freeze_encoder(model):
    for n, p in model.named_parameters():
        if "encoder" in n:
            p.requires_grad = False

# %% ../nbs/utils.ipynb 7
def process_output(output):
    if isinstance(output, str):
        output = [output]

    outputs_x = []
    outputs_y = []
    
    for text in output:
        
        outputs_x.append(";".join([xy.split("|")[0].strip() for xy in text.split("<0x0A>")[1:] if "|" in xy]))
        outputs_y.append(";".join([xy.split("|")[1].strip() for xy in text.split("<0x0A>")[1:] if "|" in xy]))
        
    
    return outputs_x, outputs_y
